name: Build and push Docker image with custom tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'

permissions:
  packages: write

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Checkout specific tag
        run: git checkout tags/v${{ github.event.inputs.tag }}

      - name: Run Snyk to check for code vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: code test
          args: --sarif-file-output=snyk-code.sarif --severity-threshold=high

      # - name: Check SARIF for critical vulnerabilities
      #   run: |
      #     # Parse the SARIF report to check for critical vulnerabilities
      #     CRITICAL_COUNT=$(jq '[.runs[].results[] | select(.level == "error")] | length' snyk-report.sarif)
      #     echo "Number of critical vulnerabilities found: $CRITICAL_COUNT"
      #     if [ "$CRITICAL_COUNT" -gt 0 ]; then
      #       echo "Critical vulnerabilities found! Failing pipeline."
      #       exit 1
      #     fi
      #   shell: bash

      - name: Run Snyk to check for dependency vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: monitor

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          GITHUB_REPO="${GITHUB_REPO,,}"  # convert repo name to lowercase as required by docker
          TAG=${{ github.event.inputs.tag }}
          echo "building docker image in repository '$GITHUB_REPO' with tag '$TAG' ..."
          docker build --label "org.opencontainers.image.title=copilot-metrics-viewer" --label "org.opencontainers.image.description=Metrics viewer for GitHub Copilot usage" --label "org.opencontainers.image.source=$GITHUB_REPO" -t ghcr.io/$GITHUB_REPO:$TAG .
          docker push ghcr.io/$GITHUB_REPO:$TAG
        env:
          GITHUB_REPO: ${{ github.repository }}
  
      - name: Run Snyk to check for container vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: code test ghcr.io/$GITHUB_REPO:$TAG
          args: --sarif-file-output=snyk-container.sarif --file=Dockerfile --severity-threshold=critical

      - name: Upload sarif files
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "**/*.sarif"